# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.ant_steps: '%env(APP_ANT_STEPS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Import the controller
    Kachuru\Zone\Controller\ZoneController:
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Kachuru\Zone\:
        resource: '../src/Kachuru/Zone/*'

    Kachuru\Util\:
        resource: '../vendor/kachuru/util/src/Kachuru/Util/*'

    Kachuru\MapMaker\:
        resource: '../vendor/kachuru/map-maker/src/Kachuru/MapMaker/*'

    Kachuru\MapMaker\MapSize:
        class: Kachuru\MapMaker\MapSize
        arguments:
            - '%env(APP_MAP_SIZE_WIDTH)%'
            - '%env(APP_MAP_SIZE_HEIGHT)%'

    Kachuru\Zone\Twig\Map\TilePosition:
        class: Kachuru\Zone\Twig\Map\TilePosition
        arguments:
            - '%env(APP_MAP_TILE_LEFT_OFFSET)%'
            - '%env(APP_MAP_TILE_TOP_OFFSET)%'
